/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  admin_account: () => import("@/views/admin/account/index.vue"),
  admin_company: () => import("@/views/admin/company/index.vue"),
  admin_subscription: () => import("@/views/admin/subscription/index.vue"),
  company: () => import("@/views/company/index.vue"),
  finance: () => import("@/views/finance/index.vue"),
  home: () => import("@/views/home/index.vue"),
  inventory_dashboard: () => import("@/views/inventory/dashboard/index.vue"),
  inventory_sheet: () => import("@/views/inventory/sheet/index.vue"),
  order: () => import("@/views/order/index.vue"),
  print: () => import("@/views/print/index.vue"),
  purchase: () => import("@/views/purchase/index.vue"),
  report: () => import("@/views/report/index.vue"),
};
