/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin',
    path: '/admin',
    component: 'layout.base',
    meta: {
      title: 'admin',
      i18nKey: 'route.admin'
    },
    children: [
      {
        name: 'admin_account',
        path: '/admin/account',
        component: 'view.admin_account',
        meta: {
          title: 'admin_account',
          i18nKey: 'route.admin_account'
        }
      },
      {
        name: 'admin_company',
        path: '/admin/company',
        component: 'view.admin_company',
        meta: {
          title: 'admin_company',
          i18nKey: 'route.admin_company'
        }
      },
      {
        name: 'admin_subscription',
        path: '/admin/subscription',
        component: 'view.admin_subscription',
        meta: {
          title: 'admin_subscription',
          i18nKey: 'route.admin_subscription'
        }
      }
    ]
  },
  {
    name: 'company',
    path: '/company',
    component: 'layout.base$view.company',
    meta: {
      title: 'company',
      i18nKey: 'route.company'
    }
  },
  {
    name: 'finance',
    path: '/finance',
    component: 'layout.base$view.finance',
    meta: {
      title: 'finance',
      i18nKey: 'route.finance'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'inventory',
    path: '/inventory',
    component: 'layout.base',
    meta: {
      title: 'inventory',
      i18nKey: 'route.inventory'
    },
    children: [
      {
        name: 'inventory_dashboard',
        path: '/inventory/dashboard',
        component: 'view.inventory_dashboard',
        meta: {
          title: 'inventory_dashboard',
          i18nKey: 'route.inventory_dashboard'
        }
      },
      {
        name: 'inventory_sheet',
        path: '/inventory/sheet',
        component: 'view.inventory_sheet',
        meta: {
          title: 'inventory_sheet',
          i18nKey: 'route.inventory_sheet'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base$view.order',
    meta: {
      title: 'order',
      i18nKey: 'route.order'
    }
  },
  {
    name: 'print',
    path: '/print',
    component: 'layout.base$view.print',
    meta: {
      title: 'print',
      i18nKey: 'route.print'
    }
  },
  {
    name: 'purchase',
    path: '/purchase',
    component: 'layout.base$view.purchase',
    meta: {
      title: 'purchase',
      i18nKey: 'route.purchase'
    }
  },
  {
    name: 'report',
    path: '/report',
    component: 'layout.base$view.report',
    meta: {
      title: 'report',
      i18nKey: 'route.report'
    }
  }
];
